stages:
  - test
  - validate
  - plan
  - apply
  - destroy

image: hashicorp/terraform:1.1.5

# .init:
#   before_script:
#     - |
#       mkdir /root/.terraform.d && cat <<-EOF > /root/.terraform.d/credentials.tfrc.json
#       {
#         "credentials": {
#           "app.terraform.io": {
#             "token": "${TF_CLOUD_TOKEN}"
#           }
#         }
#       }
#       EOF
#     - |
#       mkdir /root/.aws && cat <<-EOF > /root/.aws/credentials
#       [default]
#       aws_access_key_id = ${AWS_ACCESS_KEY_ID}
#       aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}

#       [terraform]
#       role_arn = arn:aws:iam::964066691632:role/administrator
#       source_profile = default
#       role_session_name = gitlab
#       EOF
#     - terraform init

format:
  stage: test
  script:
    - terraform fmt -check
  tags:
    - homelab

lint:
  stage: test
  image: ghcr.io/terraform-linters/tflint:latest
  script:
    - tflint --enable-plugin=aws
  tags:
    - homelab
# validate:
#   stage: validate
#   extends:
#     - .init
#   script:
#     - terraform validate
#   tags:
#     - homelab

# plan:
#   stage: plan
#   extends:
#     - .init
#   script:
#     - terraform plan -out=plan
#   tags:
#     - homelab

# apply:
#   stage: apply
#   extends:
#     - .init
#   when: manual
#   script:
#     - terraform apply -input=false -auto-approve plan
#   tags:
#     - homelab

# destroy:
#   stage: destroy
#   extends:
#     - .init
#   when: manual
#   script:
#     - terraform destroy -auto-approve
#   tags:
#     - homelab
